version: '3'
services:

  server:
    image: server
    container_name: server
    ports:
      - 8080:8080/tcp
    restart: always
    build:
      context: .
      dockerfile: server/Dockerfile
    cap_drop: 
      - all
    read_only: true
    security_opt:
      - "no-new-privileges=true"

  api:
    image: api
    container_name: api
    ports:
      - 3030:3030/tcp
    expose:
      - 3030
    restart: always
    build:
      context: .
      dockerfile: api/Dockerfile
    cap_drop: 
      - all
    read_only: true
    security_opt:
      - "no-new-privileges=true"