version: '3'
services:

  server:
    image: server
    container_name: server
    ports:
      - 80:8080
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    cap_drop: 
      - all
    pid: "host"