package main

import (
	"embed"
	"io/fs"
	"log"
	"net/http"
	"os"
	"path"
	"strings"
)

//go:embed all:out
//go:embed all:out/_next
//go:embed all:out/_next/static/chunks/pages/*.js
//go:embed all:out/_next/static/*/*.js
var nextFS embed.FS

var port = ":8080"

var page404 = "404.html"

type FSHandler404 = func(w http.ResponseWriter, r *http.Request) (doDefaultFileServe bool)

func fileSystem404(w http.ResponseWriter, r *http.Request) (doDefaultFileServe bool) {
	//if not found redirect to /missing.html
	http.Redirect(w, r, page404, http.StatusFound)
	return true
}

func FileServerWith404(root http.FileSystem, handler404 FSHandler404) http.Handler {
	fs := http.FileServer(root)

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		upath := r.URL.Path
		if !strings.HasPrefix(upath, "/") {
			upath = "/" + upath
			r.URL.Path = upath
		}
		upath = path.Clean(upath)

		f, err := root.Open(upath)
		if err != nil {
			if os.IsNotExist(err) {
				if handler404 != nil {
					if doDefault := handler404(w, r); !doDefault {
						return
					}
				}
			}
		}

		if err == nil {
			f.Close()
		}

		fs.ServeHTTP(w, r)
	})
}

func main() {
	// Root at the `dist` folder generated by the Next.js app.
	distFS, err := fs.Sub(nextFS, "out")
	if err != nil {
		log.Fatal(err)
	}

	fs := FileServerWith404(http.FS(distFS), fileSystem404)
	http.Handle("/", fs)

	log.Printf("listening on %s", port)
	log.Fatal(http.ListenAndServe(port, nil))
}
